// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LoncotesLibrary.Migrations
{
    [DbContext(typeof(LoncotesLibraryDbContext))]
    partial class LoncotesLibraryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LoncotesLibrary.Models.Checkout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckoutDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<int>("PatronId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("PatronId");

                    b.ToTable("Checkouts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CheckoutDate = new DateTime(2023, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialId = 12,
                            PatronId = 1
                        },
                        new
                        {
                            Id = 2,
                            CheckoutDate = new DateTime(2023, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialId = 13,
                            PatronId = 2
                        },
                        new
                        {
                            Id = 3,
                            CheckoutDate = new DateTime(2023, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialId = 14,
                            PatronId = 3
                        },
                        new
                        {
                            Id = 4,
                            CheckoutDate = new DateTime(2023, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialId = 15,
                            PatronId = 4
                        },
                        new
                        {
                            Id = 5,
                            CheckoutDate = new DateTime(2023, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialId = 16,
                            PatronId = 5
                        },
                        new
                        {
                            Id = 6,
                            CheckoutDate = new DateTime(2023, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialId = 17,
                            PatronId = 6
                        },
                        new
                        {
                            Id = 7,
                            CheckoutDate = new DateTime(2023, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialId = 18,
                            PatronId = 7
                        },
                        new
                        {
                            Id = 8,
                            CheckoutDate = new DateTime(2023, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialId = 19,
                            PatronId = 8
                        },
                        new
                        {
                            Id = 9,
                            CheckoutDate = new DateTime(2023, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialId = 20,
                            PatronId = 9
                        },
                        new
                        {
                            Id = 10,
                            CheckoutDate = new DateTime(2023, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialId = 21,
                            PatronId = 10
                        },
                        new
                        {
                            Id = 11,
                            CheckoutDate = new DateTime(2023, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialId = 22,
                            PatronId = 11
                        },
                        new
                        {
                            Id = 12,
                            CheckoutDate = new DateTime(2023, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialId = 23,
                            PatronId = 12
                        },
                        new
                        {
                            Id = 13,
                            CheckoutDate = new DateTime(2023, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialId = 24,
                            PatronId = 1
                        },
                        new
                        {
                            Id = 14,
                            CheckoutDate = new DateTime(2023, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialId = 25,
                            PatronId = 2
                        },
                        new
                        {
                            Id = 15,
                            CheckoutDate = new DateTime(2023, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialId = 26,
                            PatronId = 3
                        },
                        new
                        {
                            Id = 16,
                            CheckoutDate = new DateTime(2023, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialId = 27,
                            PatronId = 4
                        },
                        new
                        {
                            Id = 17,
                            CheckoutDate = new DateTime(2023, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialId = 28,
                            PatronId = 5
                        },
                        new
                        {
                            Id = 18,
                            CheckoutDate = new DateTime(2023, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialId = 29,
                            PatronId = 6
                        },
                        new
                        {
                            Id = 19,
                            CheckoutDate = new DateTime(2023, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialId = 30,
                            PatronId = 7
                        },
                        new
                        {
                            Id = 20,
                            CheckoutDate = new DateTime(2023, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialId = 31,
                            PatronId = 8,
                            ReturnDate = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            CheckoutDate = new DateTime(2023, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialId = 1,
                            PatronId = 9,
                            ReturnDate = new DateTime(2023, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            CheckoutDate = new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialId = 2,
                            PatronId = 10,
                            ReturnDate = new DateTime(2023, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            CheckoutDate = new DateTime(2023, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialId = 3,
                            PatronId = 11,
                            ReturnDate = new DateTime(2023, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            CheckoutDate = new DateTime(2023, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialId = 4,
                            PatronId = 12,
                            ReturnDate = new DateTime(2023, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            CheckoutDate = new DateTime(2023, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialId = 5,
                            PatronId = 1,
                            ReturnDate = new DateTime(2023, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            CheckoutDate = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialId = 6,
                            PatronId = 2,
                            ReturnDate = new DateTime(2023, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            CheckoutDate = new DateTime(2023, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialId = 7,
                            PatronId = 3,
                            ReturnDate = new DateTime(2023, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            CheckoutDate = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialId = 8,
                            PatronId = 4,
                            ReturnDate = new DateTime(2023, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            CheckoutDate = new DateTime(2023, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialId = 9,
                            PatronId = 5,
                            ReturnDate = new DateTime(2023, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            CheckoutDate = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialId = 10,
                            PatronId = 6,
                            ReturnDate = new DateTime(2023, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 31,
                            CheckoutDate = new DateTime(2022, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialId = 11,
                            PatronId = 7,
                            ReturnDate = new DateTime(2022, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 32,
                            CheckoutDate = new DateTime(2022, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialId = 12,
                            PatronId = 8,
                            ReturnDate = new DateTime(2022, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 33,
                            CheckoutDate = new DateTime(2022, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialId = 13,
                            PatronId = 9,
                            ReturnDate = new DateTime(2022, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 34,
                            CheckoutDate = new DateTime(2022, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialId = 14,
                            PatronId = 10,
                            ReturnDate = new DateTime(2022, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 35,
                            CheckoutDate = new DateTime(2022, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialId = 15,
                            PatronId = 11,
                            ReturnDate = new DateTime(2022, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 36,
                            CheckoutDate = new DateTime(2022, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialId = 16,
                            PatronId = 12,
                            ReturnDate = new DateTime(2022, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 37,
                            CheckoutDate = new DateTime(2022, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialId = 17,
                            PatronId = 1,
                            ReturnDate = new DateTime(2022, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 38,
                            CheckoutDate = new DateTime(2022, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialId = 18,
                            PatronId = 2,
                            ReturnDate = new DateTime(2022, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 39,
                            CheckoutDate = new DateTime(2022, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialId = 19,
                            PatronId = 3,
                            ReturnDate = new DateTime(2022, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 40,
                            CheckoutDate = new DateTime(2022, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialId = 20,
                            PatronId = 4,
                            ReturnDate = new DateTime(2022, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 41,
                            CheckoutDate = new DateTime(2022, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaterialId = 21,
                            PatronId = 5,
                            ReturnDate = new DateTime(2022, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("LoncotesLibrary.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Historical Fiction"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Biography/Autobiography"
                        });
                });

            modelBuilder.Entity("LoncotesLibrary.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaterialTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("OutOfCirculationSince")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("MaterialTypeId");

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GenreId = 6,
                            MaterialName = "The Magic Mountain",
                            MaterialTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            GenreId = 2,
                            MaterialName = "Interstellar Soundtrack",
                            MaterialTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            GenreId = 3,
                            MaterialName = "Nature's Wonders",
                            MaterialTypeId = 3
                        },
                        new
                        {
                            Id = 4,
                            GenreId = 2,
                            MaterialName = "Inception",
                            MaterialTypeId = 4
                        },
                        new
                        {
                            Id = 5,
                            GenreId = 6,
                            MaterialName = "The Odyssey Audiobook",
                            MaterialTypeId = 5
                        },
                        new
                        {
                            Id = 6,
                            GenreId = 1,
                            MaterialName = "The Enchanted Forest",
                            MaterialTypeId = 1
                        },
                        new
                        {
                            Id = 7,
                            GenreId = 2,
                            MaterialName = "Science Today",
                            MaterialTypeId = 3
                        },
                        new
                        {
                            Id = 8,
                            GenreId = 4,
                            MaterialName = "Classical Melodies",
                            MaterialTypeId = 2
                        },
                        new
                        {
                            Id = 9,
                            GenreId = 2,
                            MaterialName = "Jurassic Park",
                            MaterialTypeId = 4
                        },
                        new
                        {
                            Id = 10,
                            GenreId = 6,
                            MaterialName = "To Kill a Mockingbird Audiobook",
                            MaterialTypeId = 5
                        },
                        new
                        {
                            Id = 11,
                            GenreId = 2,
                            MaterialName = "Galaxy Exploration",
                            MaterialTypeId = 1
                        },
                        new
                        {
                            Id = 12,
                            GenreId = 3,
                            MaterialName = "The Invisible Man",
                            MaterialTypeId = 1,
                            OutOfCirculationSince = new DateTime(2023, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            GenreId = 4,
                            MaterialName = "Beethoven's Symphony",
                            MaterialTypeId = 2,
                            OutOfCirculationSince = new DateTime(2023, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            GenreId = 7,
                            MaterialName = "Modern Art Today",
                            MaterialTypeId = 3,
                            OutOfCirculationSince = new DateTime(2023, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            GenreId = 2,
                            MaterialName = "The Matrix",
                            MaterialTypeId = 4,
                            OutOfCirculationSince = new DateTime(2023, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            GenreId = 4,
                            MaterialName = "Pride and Prejudice Audiobook",
                            MaterialTypeId = 5,
                            OutOfCirculationSince = new DateTime(2023, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            GenreId = 1,
                            MaterialName = "Dragon's Realm",
                            MaterialTypeId = 1,
                            OutOfCirculationSince = new DateTime(2023, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            GenreId = 4,
                            MaterialName = "Guitar Classics",
                            MaterialTypeId = 2,
                            OutOfCirculationSince = new DateTime(2023, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            GenreId = 2,
                            MaterialName = "Tech Innovations",
                            MaterialTypeId = 3,
                            OutOfCirculationSince = new DateTime(2023, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            GenreId = 5,
                            MaterialName = "Shawshank Redemption",
                            MaterialTypeId = 4,
                            OutOfCirculationSince = new DateTime(2023, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            GenreId = 6,
                            MaterialName = "The Great Gatsby Audiobook",
                            MaterialTypeId = 5,
                            OutOfCirculationSince = new DateTime(2023, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            GenreId = 2,
                            MaterialName = "Futuristic Visions",
                            MaterialTypeId = 1,
                            OutOfCirculationSince = new DateTime(2023, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            GenreId = 3,
                            MaterialName = "Murder on the Orient Express",
                            MaterialTypeId = 1,
                            OutOfCirculationSince = new DateTime(2023, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            GenreId = 4,
                            MaterialName = "Jazz Nights",
                            MaterialTypeId = 2,
                            OutOfCirculationSince = new DateTime(2023, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            GenreId = 7,
                            MaterialName = "Historical Review",
                            MaterialTypeId = 3,
                            OutOfCirculationSince = new DateTime(2023, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            GenreId = 2,
                            MaterialName = "Star Wars",
                            MaterialTypeId = 4,
                            OutOfCirculationSince = new DateTime(2023, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            GenreId = 2,
                            MaterialName = "1984 Audiobook",
                            MaterialTypeId = 5,
                            OutOfCirculationSince = new DateTime(2023, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            GenreId = 1,
                            MaterialName = "Alice in Wonderland",
                            MaterialTypeId = 1,
                            OutOfCirculationSince = new DateTime(2023, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            GenreId = 4,
                            MaterialName = "Opera Classics",
                            MaterialTypeId = 2,
                            OutOfCirculationSince = new DateTime(2023, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            GenreId = 7,
                            MaterialName = "World News Weekly",
                            MaterialTypeId = 3,
                            OutOfCirculationSince = new DateTime(2023, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 31,
                            GenreId = 1,
                            MaterialName = "Harry Potter Series",
                            MaterialTypeId = 1,
                            OutOfCirculationSince = new DateTime(2023, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("LoncotesLibrary.Models.MaterialType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CheckoutDays")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MaterialTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CheckoutDays = 7,
                            Name = "Book"
                        },
                        new
                        {
                            Id = 2,
                            CheckoutDays = 5,
                            Name = "CD"
                        },
                        new
                        {
                            Id = 3,
                            CheckoutDays = 2,
                            Name = "Periodical"
                        },
                        new
                        {
                            Id = 4,
                            CheckoutDays = 3,
                            Name = "DVD"
                        },
                        new
                        {
                            Id = 5,
                            CheckoutDays = 7,
                            Name = "Audiobook"
                        });
                });

            modelBuilder.Entity("LoncotesLibrary.Models.Patron", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Patrons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "456 Library St, Booktown, USA 12345",
                            Email = "alice.smith@email.com",
                            FirstName = "Alice",
                            IsActive = true,
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 2,
                            Address = "789 Reading Ave, Litville, USA 67890",
                            Email = "michael.johnson@email.com",
                            FirstName = "Michael",
                            IsActive = true,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 3,
                            Address = "101 Novel Rd, Storyville, USA 23456",
                            Email = "emily.brown@email.com",
                            FirstName = "Emily",
                            IsActive = true,
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 4,
                            Address = "202 Fable Dr, Narrativetown, USA 34567",
                            Email = "david.wilson@email.com",
                            FirstName = "David",
                            IsActive = false,
                            LastName = "Wilson"
                        },
                        new
                        {
                            Id = 5,
                            Address = "303 Tale Ct, Fictioncity, USA 45678",
                            Email = "sara.miller@email.com",
                            FirstName = "Sara",
                            IsActive = true,
                            LastName = "Miller"
                        },
                        new
                        {
                            Id = 6,
                            Address = "404 Legend Ln, Mythosburg, USA 56789",
                            Email = "james.davis@email.com",
                            FirstName = "James",
                            IsActive = false,
                            LastName = "Davis"
                        },
                        new
                        {
                            Id = 7,
                            Address = "505 Epic St, Fabulaville, USA 67890",
                            Email = "angela.garcia@email.com",
                            FirstName = "Angela",
                            IsActive = true,
                            LastName = "Garcia"
                        },
                        new
                        {
                            Id = 8,
                            Address = "606 Chronicle Ave, Allegorytown, USA 78901",
                            Email = "robert.martinez@email.com",
                            FirstName = "Robert",
                            IsActive = false,
                            LastName = "Martinez"
                        },
                        new
                        {
                            Id = 9,
                            Address = "707 Saga Pl, Prosetown, USA 89012",
                            Email = "lisa.hernandez@email.com",
                            FirstName = "Lisa",
                            IsActive = true,
                            LastName = "Hernandez"
                        },
                        new
                        {
                            Id = 10,
                            Address = "808 Narrative Rd, Storyburgh, USA 90123",
                            Email = "mark.lopez@email.com",
                            FirstName = "Mark",
                            IsActive = true,
                            LastName = "Lopez"
                        },
                        new
                        {
                            Id = 11,
                            Address = "909 Fable Blvd, Plotville, USA 01234",
                            Email = "sophia.lee@email.com",
                            FirstName = "Sophia",
                            IsActive = false,
                            LastName = "Lee"
                        },
                        new
                        {
                            Id = 12,
                            Address = "1010 Myth St, Genretown, USA 12345",
                            Email = "kevin.clark@email.com",
                            FirstName = "Kevin",
                            IsActive = true,
                            LastName = "Clark"
                        });
                });

            modelBuilder.Entity("LoncotesLibrary.Models.Checkout", b =>
                {
                    b.HasOne("LoncotesLibrary.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoncotesLibrary.Models.Patron", "Patron")
                        .WithMany()
                        .HasForeignKey("PatronId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Patron");
                });

            modelBuilder.Entity("LoncotesLibrary.Models.Material", b =>
                {
                    b.HasOne("LoncotesLibrary.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoncotesLibrary.Models.MaterialType", "MaterialType")
                        .WithMany()
                        .HasForeignKey("MaterialTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("MaterialType");
                });
#pragma warning restore 612, 618
        }
    }
}
